// APP
// ======================================================
export const INIT_TCP_CLIENT = 'INIT_TCP_CLIENT';
export const SELECT_PRODUCT = 'SELECT_PRODUCT';
export const SELECT_PROMOTION_SET = 'SELECT_PROMOTION_SET';
export const RECEIVED_CASH_COMPLETELY = 'RECEIVED_CASH_COMPLETELY';
export const RESET_PAYMENT_REDUCER = 'RESET_PAYMENT_REDUCER';
export const CLEAR_PAYMENT_AMOUNT = 'CLEAR_PAYMENT_AMOUNT';
export const SELECT_MOBILE_TOPUP_PROVIDER = 'SELECT_TOPUP_PROVIDER';
export const CONFIRM_MOBILE_TOPUP_MSISDN = 'CONFIRM_MOBILE_TOPUP_MSISDN';
export const RECEIVED_CASH_REMAINING = 'RECEIVED_CASH_REMAINING';
export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';
export const HIDE_ALL_MODAL = 'HIDE_ALL_MODAL';
export const READY_TO_DROP_PRODUCT = 'READY_TO_DROP_PRODUCT';
export const NOT_READY_TO_DROP_PRODUCT = 'NOT_READY_TO_DROP_PRODUCT';
export const CLEAR_ORDER = 'CLEAR_ORDER';
export const DROPPING_PRODUCT = 'DROPPING_PRODUCT';
export const SELECT_MOBILE_TOPUP_VALUE = 'SELECT_MOBILE_TOPUP_VALUE';
export const SUBMIT_MOBILE_TOPUP_VALUE = 'SUBMIT_MOBILE_TOPUP_VALUE';
export const CLEAR_MOBILE_TOPUP_VALUE = 'CLEAR_MOBILE_TOPUP_VALUE';
export const SET_CASH_CHANGE_AMOUNT = 'SET_CASH_CHANGE_AMOUNT';
export const CLEAR_MOBILE_TOPUP_MSISDN = 'CLEAR_MOBILE_TOPUP_MSISDN';
export const SELECT_EVENT = 'SELECT_EVENT';
export const ADD_DISCOUNT = 'ADD_DISCOUNT';
export const SET_CAN_CHANGE_CASH = 'SET_CAN_CHANGE_CASH';
export const RECEIVED_MASTERDATA = 'RECEIVED_MASTERDATA';
export const EVENT_UPDATE_INPUT_VALUE = 'EVENT_UPDATE_INPUT_VALUE';
export const SET_LIMIT_BANKNOTE = 'SET_LIMIT_BANKNOTE';
export const OPEN_ALERT_MESSAGE = 'OPEN_ALERT_MESSAGE';
export const CLOSE_ALERT_MESSAGE = 'CLOSE_ALERT_MESSAGE';
export const ACTIVE_MONEY_BOX = 'ACTIVE_MONEY_BOX';
export const DEACTIVE_MONEY_BOX = 'DEACTIVE_MONEY_BOX';
export const SHOW_LOADING = 'SHOW_LOADING';
export const HIDE_LOADING = 'HIDE_LOADING';
export const SET_FOOTER_ADS = 'SET_FOOTER_ADS';
export const RESET_FOOTER_ADS = 'RESET_FOOTER_ADS';
export const USE_DISCOUNT_INSTANTLY = 'USE_DISCOUNT_INSTANTLY';
export const CLEAR_INSTANTLY_DISCOUNT = 'CLEAR_INSTANTLY_DISCOUNT';
export const SET_BASE_ADS = 'SET_BASE_ADS';
export const SET_ACTIVITY_FREE_RULE = 'SET_ACTIVITY_FREE_RULE';
export const SWITCH_LANGUAGE_TO = 'SWITCH_LANGUAGE_TO';
export const EVENT_UPDATE_REWARD_DISCOUNT = 'EVENT_UPDATE_REWARD_DISCOUNT';
export const ORDER_PRODUCT_REMOVE = 'ORDER_PRODUCT_REMOVE';
// ======================================================
// TCP
// ======================================================
export const HARDWARE_READY = 'HARDWARE_READY';
export const RECEIVED_SENSOR_INFORMATION = 'RECEIVED_SENSOR_INFORMATION';
export const RECEIVED_CASH = 'RECEIVED_CASH';
export const PRODUCT_DROP_SUCCESS = 'PRODUCT_DROP_SUCCESS';
export const PRODUCT_DROP_PROCESS_COMPLETELY = 'PRODUCT_DROP_PROCESS_COMPLETELY';
