// APP
// ======================================================
export const INIT_TCP_CLIENT = 'INIT_TCP_CLIENT';
export const SELECT_PRODUCT = 'SELECT_PRODUCT';
export const SELECT_PROMOTION_SET = 'SELECT_PROMOTION_SET';
export const RECEIVED_CASH_COMPLETELY = 'RECEIVED_CASH_COMPLETELY';
export const RESET_PAYMENT_REDUCER = 'RESET_PAYMENT_REDUCER';
export const CLEAR_PAYMENT_AMOUNT = 'CLEAR_PAYMENT_AMOUNT';
export const SELECT_MOBILE_TOPUP_PROVIDER = 'SELECT_TOPUP_PROVIDER';
export const CONFIRM_MOBILE_TOPUP_MSISDN = 'CONFIRM_MOBILE_TOPUP_MSISDN';
export const RECEIVED_CASH_REMAINING = 'RECEIVED_CASH_REMAINING';
export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';
export const HIDE_ALL_MODAL = 'HIDE_ALL_MODAL';
export const READY_TO_DROP_PRODUCT = 'READY_TO_DROP_PRODUCT';
export const NOT_READY_TO_DROP_PRODUCT = 'NOT_READY_TO_DROP_PRODUCT';
export const CLEAR_ORDER = 'CLEAR_ORDER';
export const DROPPING_PRODUCT = 'DROPPING_PRODUCT';
// ======================================================
// TCP
// ======================================================
export const RECEIVED_SENSOR_INFORMATION = 'RECEIVED_SENSOR_INFORMATION';
export const RECEIVED_CASH = 'RECEIVED_CASH';
export const PRODUCT_DROP_SUCCESS = 'PRODUCT_DROP_SUCCESS';
export const PRODUCT_DROP_PROCESS_COMPLETELY = 'PRODUCT_DROP_PROCESS_COMPLETELY';
