export default {
  mobileTopup: 'topup/MobileTopup.php',
  verifyDiscount: 'api/main.php',
  verifyBarcodeOrQrcode: 'api/main.php',
  verifyLineId: 'api/main.php',
  useLineId: 'api/main.php',
  getEvents: 'api/main.php',
  getEventReward: 'api/main.php',
  getProducts: 'api/main.php',
  getPromotions: 'api/main.php',
  getMobileTopupProviders: 'api/main.php',
  getActivityFreeRule: 'api/main.php',
  submitOrder: 'api/main.php',
  sumOrderAmount: 'api/main.php',
  getProductSteps: 'api/main.php',
  getEventSteps: 'api/main.php',
  getMobileTopupSteps: 'api/main.php',
  getMainMenu: 'api/main.php',
  verifySalesman: 'api/main.php',
  syncSettlement: 'api/main.php',
  updateStock: 'api/main.php',
  getMachineId: 'api/main.php'
};
